"""
WandaTools — routes/export.py
Server-side PDF export for the three financial pillars.

Routes (all require JWT Bearer auth):
  GET /api/v1/export/loan-readiness
  GET /api/v1/export/investment-worthiness
  GET /api/v1/export/tax-compliance

Query params:
  year       int  Fiscal year, e.g. 2025  (default: current year)
  start_date str  YYYY-MM-DD range start  (optional, overrides year)
  end_date   str  YYYY-MM-DD range end    (optional, overrides year)
"""

import io
import logging
import math
import re
from collections import defaultdict
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from db import get_db
from main import User
from routes.auth import get_current_user
from routes.transactions import Transaction

# ── ReportLab ─────────────────────────────────────────────────
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.platypus import (
    HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

log    = logging.getLogger("wandatools.export")
router = APIRouter(prefix="/api/v1/export", tags=["Export"])

# ── Page geometry ──────────────────────────────────────────────
PAGE_W, PAGE_H = A4
MARGIN    = 1.5 * cm
USABLE_W  = PAGE_W - 2 * MARGIN   # ≈ 510 pt

# ── Brand colours ──────────────────────────────────────────────
C_BLUE   = colors.HexColor("#007BFF")
C_ORANGE = colors.HexColor("#FF6F00")
C_GREEN  = colors.HexColor("#28A745")
C_RED    = colors.HexColor("#DC3545")
C_DARK   = colors.HexColor("#1A1A2E")
C_MID    = colors.HexColor("#6C757D")
C_LIGHT  = colors.HexColor("#F8F9FA")
C_WHITE  = colors.white
C_BORDER = colors.HexColor("#DEE2E6")


# ══════════════════════════════════════════════════════════════════
# FOOTER CANVAS — page numbers + confidentiality on every page
# ══════════════════════════════════════════════════════════════════

class _FooterCanvas(rl_canvas.Canvas):
    def __init__(self, *args, generated_at: str = "", **kwargs):
        rl_canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states: list = []
        self._generated_at = generated_at

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_footer(total)
            rl_canvas.Canvas.showPage(self)
        rl_canvas.Canvas.save(self)

    def _draw_footer(self, total: int) -> None:
        pg = self._pageNumber
        self.saveState()
        # Light strip
        self.setFillColor(C_LIGHT)
        self.rect(0, 0, PAGE_W, 1.5 * cm, fill=1, stroke=0)
        # Blue rule above strip
        self.setStrokeColor(C_BLUE)
        self.setLineWidth(0.75)
        self.line(MARGIN, 1.6 * cm, PAGE_W - MARGIN, 1.6 * cm)
        # Confidentiality notice
        self.setFont("Helvetica-Oblique", 6.5)
        self.setFillColor(C_MID)
        self.drawString(
            MARGIN, 0.65 * cm,
            f"Generated by WandaTools – Confidential  |  "
            f"Auto-generated from WandaTools data as of {self._generated_at}",
        )
        # Page number
        self.setFont("Helvetica-Bold", 7)
        self.setFillColor(C_DARK)
        self.drawRightString(PAGE_W - MARGIN, 0.65 * cm, f"Page {pg} of {total}")
        self.restoreState()


def _make_canvas_cls(generated_at: str):
    class _C(_FooterCanvas):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, generated_at=generated_at, **kwargs)
    return _C


# ══════════════════════════════════════════════════════════════════
# PARAGRAPH STYLES
# ══════════════════════════════════════════════════════════════════

def _styles() -> dict:
    return {
        "brand": ParagraphStyle("brand",
            fontName="Helvetica-Bold", fontSize=20, textColor=C_BLUE),
        "tagline": ParagraphStyle("tagline",
            fontName="Helvetica", fontSize=8, textColor=C_MID),
        "report_title": ParagraphStyle("report_title",
            fontName="Helvetica-Bold", fontSize=16, textColor=C_DARK, spaceAfter=2),
        "report_subtitle": ParagraphStyle("report_subtitle",
            fontName="Helvetica", fontSize=10, textColor=C_MID, spaceAfter=6),
        "section": ParagraphStyle("section",
            fontName="Helvetica-Bold", fontSize=10, textColor=C_BLUE,
            spaceBefore=10, spaceAfter=4),
        "body": ParagraphStyle("body",
            fontName="Helvetica", fontSize=9, textColor=C_DARK, leading=13),
        "disclaimer": ParagraphStyle("disclaimer",
            fontName="Helvetica-Oblique", fontSize=7.5, textColor=C_MID,
            leading=11, spaceAfter=4),
        "score_num": ParagraphStyle("score_num",
            fontName="Helvetica-Bold", fontSize=28, textColor=C_WHITE, alignment=TA_CENTER),
        "score_sub": ParagraphStyle("score_sub",
            fontName="Helvetica-Bold", fontSize=8, textColor=C_WHITE, alignment=TA_CENTER),
    }


# ══════════════════════════════════════════════════════════════════
# DATA HELPERS
# ══════════════════════════════════════════════════════════════════

def _safe_name(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", (text or "WandaTools").strip())[:28]


def _fmt(amount: float, currency: str) -> str:
    return f"{currency} {amount:,.2f}"


def _pct(num: float, denom: float) -> str:
    return f"{num / denom * 100:.1f}%" if denom else "—"


def _get_period(
    year: int,
    start_date: Optional[str],
    end_date: Optional[str],
) -> tuple:
    if start_date and end_date:
        try:
            sd = datetime.fromisoformat(start_date.replace("Z", "+00:00")).replace(tzinfo=None)
            ed = datetime.fromisoformat(end_date.replace("Z", "+00:00")).replace(tzinfo=None)
            return sd, ed
        except ValueError:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Invalid start_date or end_date — use YYYY-MM-DD",
            )
    return datetime(year, 1, 1), datetime(year, 12, 31, 23, 59, 59)


def _fetch_txns(db: Session, user_id: int, start_dt: datetime, end_dt: datetime) -> list:
    return (
        db.query(Transaction)
        .filter(
            Transaction.user_id          == user_id,
            Transaction.transaction_date >= start_dt,
            Transaction.transaction_date <= end_dt,
            Transaction.is_deleted       == False,   # noqa: E712
        )
        .order_by(Transaction.transaction_date)
        .all()
    )


def _by_cat(txns: list, txn_type: str) -> dict:
    result: dict = {}
    for t in txns:
        tv = t.type.value if hasattr(t.type, "value") else str(t.type)
        if tv == txn_type:
            result[t.category] = result.get(t.category, 0.0) + t.amount
    return dict(sorted(result.items(), key=lambda x: x[1], reverse=True))


def _monthly_flows(txns: list, start_dt: datetime, end_dt: datetime) -> dict:
    raw: dict = defaultdict(lambda: {"income": 0.0, "expense": 0.0})
    for t in txns:
        k  = t.transaction_date.strftime("%Y-%m")
        tv = t.type.value if hasattr(t.type, "value") else str(t.type)
        raw[k]["income" if tv == "income" else "expense"] += t.amount

    result = {}
    cur = datetime(start_dt.year, start_dt.month, 1)
    end = datetime(end_dt.year,   end_dt.month,   1)
    while cur <= end:
        k = cur.strftime("%Y-%m")
        d = raw.get(k, {"income": 0.0, "expense": 0.0})
        result[k] = {"income": d["income"], "expense": d["expense"],
                     "net": d["income"] - d["expense"]}
        cur = datetime(cur.year + 1, 1, 1) if cur.month == 12 else \
              datetime(cur.year, cur.month + 1, 1)
    return result


def _expense_tax_breakdown(txns: list) -> dict:
    result: dict = {}
    for t in txns:
        tv = t.type.value if hasattr(t.type, "value") else str(t.type)
        if tv == "expense":
            if t.category not in result:
                result[t.category] = [0.0, 0.0]
            result[t.category][0] += t.amount
            if t.tax_deductible:
                result[t.category][1] += t.amount
    return dict(sorted(result.items(), key=lambda x: x[1][0], reverse=True))


# ══════════════════════════════════════════════════════════════════
# SCORE ALGORITHMS
# ══════════════════════════════════════════════════════════════════

def _loan_score(total_income: float, total_expenses: float, flows: dict) -> tuple:
    score = 0
    bd: dict = {}

    # Coverage ratio (30 pts)
    ratio = (total_income / total_expenses) if total_expenses else (2.0 if total_income else 0)
    pts   = 30 if ratio >= 2.0 else 22 if ratio >= 1.5 else 15 if ratio >= 1.2 else 8 if ratio >= 1.0 else 0
    score += pts;  bd["Income Coverage Ratio"] = (pts, 30)

    # Income stability — coeff. of variation (30 pts)
    incomes = [v["income"] for v in flows.values()]
    if len(incomes) >= 2 and sum(incomes) > 0:
        m  = sum(incomes) / len(incomes)
        cv = math.sqrt(sum((x - m) ** 2 for x in incomes) / len(incomes)) / m if m else 1
        pts = 30 if cv <= 0.10 else 24 if cv <= 0.20 else 16 if cv <= 0.35 else 8 if cv <= 0.50 else 3
    else:
        pts = 10
    score += pts;  bd["Monthly Income Stability"] = (pts, 30)

    # History depth (20 pts)
    months_active = sum(1 for v in flows.values() if v["income"] > 0)
    pts = 20 if months_active >= 12 else 14 if months_active >= 6 else 8 if months_active >= 3 else 3
    score += pts;  bd["Financial History Depth"] = (pts, 20)

    # Profitability consistency (20 pts)
    n   = max(len(flows), 1)
    pct = sum(1 for v in flows.values() if v["net"] >= 0) / n
    pts = 20 if pct >= 0.90 else 15 if pct >= 0.75 else 9 if pct >= 0.50 else 3
    score += pts;  bd["Profitability Consistency"] = (pts, 20)

    score = min(score, 100)
    rating = "Excellent" if score >= 80 else "Good" if score >= 65 else "Fair" if score >= 50 else "Needs Improvement"
    return score, bd, rating


def _invest_score(total_income: float, total_expenses: float,
                  income_by_cat: dict, flows: dict) -> tuple:
    score = 0
    bd: dict = {}

    # Revenue scale (25 pts)
    pts = (25 if total_income >= 500_000 else 20 if total_income >= 100_000
           else 14 if total_income >= 50_000 else 8 if total_income >= 10_000 else 3)
    score += pts;  bd["Revenue Scale"] = (pts, 25)

    # Profit margin (25 pts)
    margin = (total_income - total_expenses) / total_income if total_income else 0
    pts    = (25 if margin >= 0.40 else 20 if margin >= 0.25 else 14 if margin >= 0.15
              else 8 if margin >= 0.05 else 3 if margin >= 0 else 0)
    score += pts;  bd["Profit Margin"] = (pts, 25)

    # Revenue diversification — inverse HHI (20 pts)
    if income_by_cat and total_income:
        shares = [v / total_income for v in income_by_cat.values()]
        pts    = min(round((1 - sum(s ** 2 for s in shares)) * 20), 20)
    else:
        pts = 0
    score += pts;  bd["Revenue Diversification"] = (pts, 20)

    # Growth trend (30 pts)
    fl = list(flows.values())
    if len(fl) >= 4:
        half = len(fl) // 2
        avg1 = sum(v["income"] for v in fl[:half])  / half
        avg2 = sum(v["income"] for v in fl[half:])  / (len(fl) - half)
        g    = (avg2 - avg1) / avg1 if avg1 else 0
        pts  = 30 if g >= 0.30 else 23 if g >= 0.15 else 16 if g >= 0.05 else 10 if g >= 0 else 4
    else:
        pts = 10
    score += pts;  bd["Revenue Growth Trend"] = (pts, 30)

    score  = min(score, 100)
    rating = "Excellent" if score >= 80 else "Good" if score >= 65 else "Fair" if score >= 50 else "Needs Improvement"
    return score, bd, rating


# ══════════════════════════════════════════════════════════════════
# PDF FLOWABLE BUILDERS
# ══════════════════════════════════════════════════════════════════

def _header(title: str, subtitle: str, user_name: str,
            period: str, generated: str, currency: str, S: dict) -> list:
    elems = []

    # Dark brand bar
    bar = Table(
        [[Paragraph("WandaTools", S["brand"]),
          Paragraph("AI-Powered Financial Management • Eswatini",
                    S["tagline"])]],
        colWidths=[USABLE_W * 0.38, USABLE_W * 0.62],
    )
    bar.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), C_DARK),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
    ]))
    elems.append(bar)
    elems.append(Spacer(1, 10))
    elems.append(Paragraph(title,    S["report_title"]))
    elems.append(Paragraph(subtitle, S["report_subtitle"]))

    # Meta info grid
    _s = lambda bold: ParagraphStyle("_", fontName=("Helvetica-Bold" if bold else "Helvetica"),
                                     fontSize=8, textColor=(C_BLUE if bold else C_DARK))
    meta = [
        [Paragraph("Business / Name", _s(True)),  Paragraph(user_name, _s(False)),
         Paragraph("Financial Period", _s(True)),  Paragraph(period,    _s(False))],
        [Paragraph("Currency",        _s(True)),  Paragraph(currency,  _s(False)),
         Paragraph("Date Generated",  _s(True)),  Paragraph(generated, _s(False))],
    ]
    mt = Table(meta, colWidths=[USABLE_W * 0.22, USABLE_W * 0.28,
                                 USABLE_W * 0.22, USABLE_W * 0.28])
    mt.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), C_LIGHT),
        ("BOX",           (0, 0), (-1, -1), 0.5, C_BORDER),
        ("INNERGRID",     (0, 0), (-1, -1), 0.25, C_BORDER),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
    ]))
    elems.append(mt)
    elems.append(Spacer(1, 6))
    elems.append(HRFlowable(width="100%", thickness=2.0, color=C_BLUE, spaceAfter=12))
    return elems


def _stat_row(stats: list, S: dict) -> list:
    n   = len(stats)
    cw  = USABLE_W / n
    top = [Paragraph(
               f'<font color="{c}">' + (f"<b>{v}</b>" if v else "—") + "</font>",
               ParagraphStyle("sv", fontName="Helvetica-Bold", fontSize=13, alignment=TA_CENTER),
           ) for _, v, c in stats]
    bot = [Paragraph(l, ParagraphStyle("sl", fontName="Helvetica", fontSize=7.5,
                                        textColor=C_MID, alignment=TA_CENTER))
           for l, _, _ in stats]
    t = Table([top, bot], colWidths=[cw] * n)
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), C_LIGHT),
        ("BACKGROUND",    (0, 1), (-1, 1), C_WHITE),
        ("BOX",           (0, 0), (-1, -1), 0.5, C_BORDER),
        ("INNERGRID",     (0, 0), (-1, -1), 0.25, C_BORDER),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
    ]))
    return [t, Spacer(1, 14)]


def _section_h(label: str, S: dict) -> list:
    return [
        Paragraph(label, S["section"]),
        HRFlowable(width="100%", thickness=0.5, color=C_BORDER, spaceAfter=6),
    ]


def _fin_table(rows: list, col_widths: list, accent=None) -> Table:
    color = accent or C_GREEN
    n     = len(rows)
    style = [
        # Header
        ("BACKGROUND",    (0, 0), (-1, 0),  C_BLUE),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  C_WHITE),
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 8.5),
        # Data rows alternating (all except header and last/total)
        *[("BACKGROUND",  (0, i), (-1, i),  C_LIGHT)
          for i in range(1, n - 1) if i % 2 == 0],
        # Total row
        ("BACKGROUND",    (0, n-1), (-1, n-1), colors.HexColor("#EBF5FB")),
        ("FONTNAME",      (0, n-1), (-1, n-1), "Helvetica-Bold"),
        ("TEXTCOLOR",     (0, n-1), (-1, n-1), color),
        ("LINEABOVE",     (0, n-1), (-1, n-1), 1.0, color),
        ("TOPPADDING",    (0, n-1), (-1, n-1), 7),
        ("BOTTOMPADDING", (0, n-1), (-1, n-1), 7),
        # All cells
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 1), (-1, n-2), 5),
        ("BOTTOMPADDING", (0, 1), (-1, n-2), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("BOX",           (0, 0), (-1, -1), 0.5, C_BORDER),
        ("LINEBELOW",     (0, 0), (-1, 0),  1.0, C_BLUE),
    ]
    # Right-align numeric columns (everything after the first)
    for col in range(1, len(col_widths)):
        style.append(("ALIGN", (col, 0), (col, -1), "RIGHT"))
    t = Table(rows, colWidths=col_widths)
    t.setStyle(TableStyle(style))
    return t


def _score_box(score: int, rating: str, breakdown: dict, S: dict) -> list:
    sc = (C_GREEN if score >= 80 else C_BLUE if score >= 65
          else C_ORANGE if score >= 50 else C_RED)

    left = Table(
        [[Paragraph(str(score), S["score_num"])],
         [Paragraph(f"/ 100 — {rating}", S["score_sub"])]],
        colWidths=[4.8 * cm],
    )
    left.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), sc),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
    ]))

    bd_rows = [["Assessment Area", "Earned", "Max"]] + [
        [k, str(v[0]), str(v[1])] for k, v in breakdown.items()
    ]
    right = Table(bd_rows, colWidths=[8.6 * cm, 2.0 * cm, 2.0 * cm])
    right.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0),  C_DARK),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  C_WHITE),
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 8.5),
        *[("BACKGROUND",  (0, i), (-1, i),  C_LIGHT)
          for i in range(1, len(bd_rows)) if i % 2 == 0],
        ("ALIGN",         (1, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("BOX",           (0, 0), (-1, -1), 0.5, C_BORDER),
        ("INNERGRID",     (0, 0), (-1, -1), 0.25, C_BORDER),
    ]))

    combo = Table([[left, right]],
                  colWidths=[4.8 * cm, USABLE_W - 4.8 * cm])
    combo.setStyle(TableStyle([
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("RIGHTPADDING",  (0, 0), (0, 0),   8),
        ("LEFTPADDING",   (1, 0), (1, 0),   0),
        ("TOPPADDING",    (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    return [combo, Spacer(1, 12)]


def _disclaimer(report_name: str, period: str, S: dict) -> list:
    text = (
        f"<b>Disclaimer:</b> This <i>{report_name}</i> is auto-generated from WandaTools "
        f"financial records for the period <b>{period}</b>. It is intended for informational "
        f"purposes only and does not constitute audited financial statements, legal advice, or "
        f"formal tax guidance. WandaTools and its affiliates accept no liability for decisions "
        f"made solely based on this report. Consult a qualified professional for formal advice."
    )
    sig = Table(
        [["Authorised Signatory", "Date", "Company Stamp / Seal"],
         ["\n\n" + "_" * 28, "\n\n" + "_" * 16, "\n\n" + "_" * 28]],
        colWidths=[USABLE_W / 3] * 3,
    )
    sig.setStyle(TableStyle([
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 8),
        ("TEXTCOLOR",     (0, 0), (-1, 0), C_MID),
        ("TOPPADDING",    (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
    ]))
    return [
        HRFlowable(width="100%", thickness=0.5, color=C_BORDER, spaceBefore=16, spaceAfter=8),
        Paragraph(text, S["disclaimer"]),
        Spacer(1, 18),
        sig,
    ]


def _build_pdf(story: list, generated_at: str) -> io.BytesIO:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN,  bottomMargin=2.2 * cm,
    )
    doc.build(story, canvasmaker=_make_canvas_cls(generated_at))
    buf.seek(0)
    return buf


def _stream(buf: io.BytesIO, filename: str) -> StreamingResponse:
    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# ══════════════════════════════════════════════════════════════════
# ROUTE 1 — LOAN READINESS ASSESSMENT
# ══════════════════════════════════════════════════════════════════

@router.get("/loan-readiness", summary="Export Loan Readiness Assessment PDF")
async def export_loan_readiness(
    year:       int           = Query(default=datetime.utcnow().year, ge=2000, le=2100),
    start_date: Optional[str] = Query(default=None),
    end_date:   Optional[str] = Query(default=None),
    db:         Session       = Depends(get_db),
    current_user: User        = Depends(get_current_user),
):
    start_dt, end_dt = _get_period(year, start_date, end_date)
    txns = _fetch_txns(db, current_user.id, start_dt, end_dt)
    if not txns:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"No transactions found for {start_dt.strftime('%b %Y')} – "
                   f"{end_dt.strftime('%b %Y')}. Add transactions before exporting.",
        )

    currency      = current_user.currency or "E"
    income_by_cat = _by_cat(txns, "income")
    expense_by_cat = _by_cat(txns, "expense")
    total_income   = sum(income_by_cat.values())
    total_expenses = sum(expense_by_cat.values())
    net_profit     = total_income - total_expenses
    flows          = _monthly_flows(txns, start_dt, end_dt)
    score, bd, rating = _loan_score(total_income, total_expenses, flows)

    period_label = f"{start_dt.strftime('%d %b %Y')} – {end_dt.strftime('%d %b %Y')}"
    generated_at = datetime.utcnow().strftime("%d %b %Y %H:%M UTC")
    S = _styles()
    story: list = []

    # ── Header ──
    story += _header(
        "Loan Readiness Assessment",
        "Financial health evaluation to support credit and lending applications",
        current_user.name or current_user.email,
        period_label, generated_at, currency, S,
    )

    # ── Summary stats ──
    margin_str = _pct(net_profit, total_income)
    story += _stat_row([
        ("Total Income",   _fmt(total_income,   currency), "#007BFF"),
        ("Total Expenses", _fmt(total_expenses, currency), "#FF6F00"),
        ("Net Profit",     _fmt(net_profit,     currency),
                           "#28A745" if net_profit >= 0 else "#DC3545"),
        ("Profit Margin",  margin_str,
                           "#28A745" if net_profit >= 0 else "#DC3545"),
    ], S)

    # ── Income Statement ──
    story += _section_h("INCOME STATEMENT", S)

    if income_by_cat:
        inc_rows = [["Income Category", "Amount", "% of Total"]]
        for cat, amt in income_by_cat.items():
            inc_rows.append([cat, _fmt(amt, currency), _pct(amt, total_income)])
        inc_rows.append(["TOTAL INCOME", _fmt(total_income, currency), "100.0%"])
        story.append(_fin_table(inc_rows, [USABLE_W*0.50, USABLE_W*0.28, USABLE_W*0.22], C_GREEN))
        story.append(Spacer(1, 10))

    if expense_by_cat:
        exp_rows = [["Expense Category", "Amount", "% of Total"]]
        for cat, amt in expense_by_cat.items():
            exp_rows.append([cat, _fmt(amt, currency), _pct(amt, total_expenses)])
        exp_rows.append(["TOTAL EXPENSES", _fmt(total_expenses, currency), "100.0%"])
        story.append(_fin_table(exp_rows, [USABLE_W*0.50, USABLE_W*0.28, USABLE_W*0.22], C_RED))
        story.append(Spacer(1, 8))

    # Net summary row
    net_row_data = [["", "Net Profit / (Loss)", _fmt(net_profit, currency)]]
    nt = Table(net_row_data, colWidths=[USABLE_W*0.50, USABLE_W*0.28, USABLE_W*0.22])
    nt.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#EBF5FB")),
        ("FONTNAME",      (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("TEXTCOLOR",     (0, 0), (-1, -1), C_GREEN if net_profit >= 0 else C_RED),
        ("ALIGN",         (2, 0), (2, 0),   "RIGHT"),
        ("TOPPADDING",    (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("BOX",           (0, 0), (-1, -1), 1.0, C_GREEN if net_profit >= 0 else C_RED),
    ]))
    story.append(nt)
    story.append(Spacer(1, 14))

    # ── Monthly Cash Flow ──
    story += _section_h("MONTHLY CASH FLOW ANALYSIS", S)
    cf_rows = [["Month", "Income", "Expenses", "Net Flow", "Cumulative"]]
    cumulative = 0.0
    for k, v in flows.items():
        cumulative += v["net"]
        label = datetime.strptime(k, "%Y-%m").strftime("%b %Y")
        cf_rows.append([
            label,
            _fmt(v["income"],  currency),
            _fmt(v["expense"], currency),
            _fmt(v["net"],     currency),
            _fmt(cumulative,   currency),
        ])
    cf_rows.append([
        "TOTAL",
        _fmt(total_income,   currency),
        _fmt(total_expenses, currency),
        _fmt(net_profit,     currency),
        "—",
    ])
    story.append(_fin_table(
        cf_rows,
        [USABLE_W*0.16, USABLE_W*0.21, USABLE_W*0.21, USABLE_W*0.21, USABLE_W*0.21],
    ))
    story.append(Spacer(1, 14))

    # ── Loan Readiness Score ──
    story += _section_h("LOAN READINESS SCORE", S)
    story += _score_box(score, rating, bd, S)

    # ── Disclaimer ──
    story += _disclaimer("Loan Readiness Assessment", period_label, S)

    today       = datetime.utcnow().strftime("%Y%m%d")
    safe        = _safe_name(current_user.name or current_user.email)
    buf         = _build_pdf(story, generated_at)
    return _stream(buf, f"LoanReadiness_{safe}_{today}.pdf")


# ══════════════════════════════════════════════════════════════════
# ROUTE 2 — INVESTMENT WORTHINESS ASSESSMENT
# ══════════════════════════════════════════════════════════════════

@router.get("/investment-worthiness", summary="Export Investment Worthiness Assessment PDF")
async def export_investment_worthiness(
    year:       int           = Query(default=datetime.utcnow().year, ge=2000, le=2100),
    start_date: Optional[str] = Query(default=None),
    end_date:   Optional[str] = Query(default=None),
    db:         Session       = Depends(get_db),
    current_user: User        = Depends(get_current_user),
):
    start_dt, end_dt = _get_period(year, start_date, end_date)
    txns = _fetch_txns(db, current_user.id, start_dt, end_dt)
    if not txns:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"No transactions found for {start_dt.strftime('%b %Y')} – "
                   f"{end_dt.strftime('%b %Y')}. Add transactions before exporting.",
        )

    currency       = current_user.currency or "E"
    income_by_cat  = _by_cat(txns, "income")
    expense_by_cat = _by_cat(txns, "expense")
    total_income   = sum(income_by_cat.values())
    total_expenses = sum(expense_by_cat.values())
    net_profit     = total_income - total_expenses
    flows          = _monthly_flows(txns, start_dt, end_dt)
    score, bd, rating = _invest_score(total_income, total_expenses, income_by_cat, flows)

    period_label = f"{start_dt.strftime('%d %b %Y')} – {end_dt.strftime('%d %b %Y')}"
    generated_at = datetime.utcnow().strftime("%d %b %Y %H:%M UTC")
    S = _styles()
    story: list = []

    # ── Header ──
    story += _header(
        "Investment Worthiness Assessment",
        "Profitability and growth analysis to attract investors and strategic partners",
        current_user.name or current_user.email,
        period_label, generated_at, currency, S,
    )

    # ── Summary stats ──
    margin_pct = (net_profit / total_income * 100) if total_income else 0
    story += _stat_row([
        ("Total Revenue",    _fmt(total_income,   currency), "#007BFF"),
        ("Net Profit",       _fmt(net_profit,     currency),
                             "#28A745" if net_profit >= 0 else "#DC3545"),
        ("Profit Margin",    f"{margin_pct:.1f}%",
                             "#28A745" if margin_pct >= 0 else "#DC3545"),
        ("Revenue Streams",  str(len(income_by_cat)), "#FF6F00"),
    ], S)

    # ── Revenue breakdown ──
    story += _section_h("REVENUE BREAKDOWN", S)
    if income_by_cat:
        rows = [["Revenue Category", "Amount", "% of Revenue"]]
        for cat, amt in income_by_cat.items():
            rows.append([cat, _fmt(amt, currency), _pct(amt, total_income)])
        rows.append(["TOTAL REVENUE", _fmt(total_income, currency), "100.0%"])
        story.append(_fin_table(rows, [USABLE_W*0.50, USABLE_W*0.28, USABLE_W*0.22], C_GREEN))
        story.append(Spacer(1, 12))

    # ── Cost structure ──
    story += _section_h("COST STRUCTURE", S)
    if expense_by_cat:
        rows = [["Expense Category", "Amount", "% of Revenue"]]
        for cat, amt in expense_by_cat.items():
            rows.append([cat, _fmt(amt, currency), _pct(amt, total_income)])
        rows.append(["TOTAL EXPENSES", _fmt(total_expenses, currency), _pct(total_expenses, total_income)])
        story.append(_fin_table(rows, [USABLE_W*0.50, USABLE_W*0.28, USABLE_W*0.22], C_RED))
        story.append(Spacer(1, 12))

    # ── Monthly performance ──
    story += _section_h("MONTHLY PERFORMANCE", S)
    perf_rows = [["Month", "Revenue", "Expenses", "Net Profit", "Margin"]]
    for k, v in flows.items():
        label  = datetime.strptime(k, "%Y-%m").strftime("%b %Y")
        margin = _pct(v["net"], v["income"]) if v["income"] else "—"
        perf_rows.append([
            label,
            _fmt(v["income"],  currency),
            _fmt(v["expense"], currency),
            _fmt(v["net"],     currency),
            margin,
        ])
    perf_rows.append([
        "TOTAL",
        _fmt(total_income,   currency),
        _fmt(total_expenses, currency),
        _fmt(net_profit,     currency),
        f"{margin_pct:.1f}%",
    ])
    story.append(_fin_table(
        perf_rows,
        [USABLE_W*0.16, USABLE_W*0.21, USABLE_W*0.21, USABLE_W*0.21, USABLE_W*0.21],
    ))
    story.append(Spacer(1, 14))

    # ── Investment score ──
    story += _section_h("INVESTMENT WORTHINESS SCORE", S)
    story += _score_box(score, rating, bd, S)

    # ── Disclaimer ──
    story += _disclaimer("Investment Worthiness Assessment", period_label, S)

    today = datetime.utcnow().strftime("%Y%m%d")
    safe  = _safe_name(current_user.name or current_user.email)
    buf   = _build_pdf(story, generated_at)
    return _stream(buf, f"InvestmentWorthiness_{safe}_{today}.pdf")


# ══════════════════════════════════════════════════════════════════
# ROUTE 3 — TAX COMPLIANCE SUMMARY
# ══════════════════════════════════════════════════════════════════

@router.get("/tax-compliance", summary="Export Tax Compliance Summary PDF")
async def export_tax_compliance(
    year:       int           = Query(default=datetime.utcnow().year, ge=2000, le=2100),
    start_date: Optional[str] = Query(default=None),
    end_date:   Optional[str] = Query(default=None),
    db:         Session       = Depends(get_db),
    current_user: User        = Depends(get_current_user),
):
    start_dt, end_dt = _get_period(year, start_date, end_date)
    txns = _fetch_txns(db, current_user.id, start_dt, end_dt)
    if not txns:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"No transactions found for {start_dt.strftime('%b %Y')} – "
                   f"{end_dt.strftime('%b %Y')}. Add transactions before exporting.",
        )

    currency       = current_user.currency or "E"
    income_by_cat  = _by_cat(txns, "income")
    tax_breakdown  = _expense_tax_breakdown(txns)   # {cat: [total, deductible]}
    total_income   = sum(income_by_cat.values())
    total_expenses = sum(v[0] for v in tax_breakdown.values())
    total_deductible   = sum(v[1] for v in tax_breakdown.values())
    taxable_income     = total_income - total_deductible

    period_label = f"{start_dt.strftime('%d %b %Y')} – {end_dt.strftime('%d %b %Y')}"
    generated_at = datetime.utcnow().strftime("%d %b %Y %H:%M UTC")
    S = _styles()
    story: list = []

    # ── Header ──
    story += _header(
        "Tax Compliance Summary",
        f"Income and expense classification for the tax year ending {end_dt.strftime('%d %b %Y')}",
        current_user.name or current_user.email,
        period_label, generated_at, currency, S,
    )

    # ── Summary stats ──
    story += _stat_row([
        ("Gross Income",         _fmt(total_income,     currency), "#007BFF"),
        ("Total Expenses",       _fmt(total_expenses,   currency), "#FF6F00"),
        ("Deductible Expenses",  _fmt(total_deductible, currency), "#28A745"),
        ("Estimated Taxable Income", _fmt(taxable_income, currency),
                                 "#007BFF" if taxable_income >= 0 else "#DC3545"),
    ], S)

    # ── Gross income by category ──
    story += _section_h("GROSS INCOME BY CATEGORY", S)
    if income_by_cat:
        rows = [["Income Category", "Amount", "% of Total Income"]]
        for cat, amt in income_by_cat.items():
            rows.append([cat, _fmt(amt, currency), _pct(amt, total_income)])
        rows.append(["TOTAL GROSS INCOME", _fmt(total_income, currency), "100.0%"])
        story.append(_fin_table(rows, [USABLE_W*0.50, USABLE_W*0.28, USABLE_W*0.22], C_GREEN))
        story.append(Spacer(1, 12))

    # ── Expense analysis with deductible breakdown ──
    story += _section_h("EXPENSE ANALYSIS", S)
    if tax_breakdown:
        rows = [["Expense Category", "Total Amount", "Tax Deductible"]]
        for cat, (total, ded) in tax_breakdown.items():
            rows.append([cat, _fmt(total, currency), _fmt(ded, currency) if ded else "—"])
        rows.append([
            "TOTAL EXPENSES",
            _fmt(total_expenses,  currency),
            _fmt(total_deductible, currency),
        ])
        story.append(_fin_table(rows, [USABLE_W*0.48, USABLE_W*0.26, USABLE_W*0.26], C_RED))
        story.append(Spacer(1, 12))

    # ── Deductible expenses ──
    deductible_cats = {c: v[1] for c, v in tax_breakdown.items() if v[1] > 0}
    if deductible_cats:
        story += _section_h("TAX-DEDUCTIBLE EXPENSES SUMMARY", S)
        deductible_sorted = dict(sorted(deductible_cats.items(), key=lambda x: x[1], reverse=True))
        rows = [["Deductible Expense Category", "Deductible Amount", "% of Total Deductible"]]
        for cat, amt in deductible_sorted.items():
            rows.append([cat, _fmt(amt, currency), _pct(amt, total_deductible)])
        rows.append(["TOTAL DEDUCTIBLE", _fmt(total_deductible, currency), "100.0%"])
        story.append(_fin_table(rows, [USABLE_W*0.50, USABLE_W*0.28, USABLE_W*0.22], C_GREEN))
        story.append(Spacer(1, 12))

    # ── Tax summary calculation ──
    story += _section_h("ESTIMATED TAX SUMMARY", S)
    tax_rows = [
        ["", "Amount"],
        ["Gross Income",                    _fmt(total_income,     currency)],
        ["Less: Total Tax-Deductible Expenses", f"({_fmt(total_deductible, currency)})"],
        ["Estimated Taxable Income",        _fmt(taxable_income,   currency)],
        ["Non-Deductible Expenses",         _fmt(total_expenses - total_deductible, currency)],
        ["Total Expenses",                  _fmt(total_expenses,   currency)],
    ]
    n = len(tax_rows)
    ts_style = [
        ("BACKGROUND",    (0, 0),  (-1, 0),  C_BLUE),
        ("TEXTCOLOR",     (0, 0),  (-1, 0),  C_WHITE),
        ("FONTNAME",      (0, 0),  (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0),  (-1, -1), 8.5),
        # Highlight taxable income row (row index 3)
        ("BACKGROUND",    (0, 3),  (-1, 3),  colors.HexColor("#EBF5FB")),
        ("FONTNAME",      (0, 3),  (-1, 3),  "Helvetica-Bold"),
        ("TEXTCOLOR",     (0, 3),  (-1, 3),  C_BLUE),
        ("LINEABOVE",     (0, 3),  (-1, 3),  1.0, C_BLUE),
        ("LINEBELOW",     (0, 3),  (-1, 3),  1.0, C_BLUE),
        *[("BACKGROUND",  (0, i),  (-1, i),  C_LIGHT) for i in range(1, n) if i % 2 == 0 and i != 3],
        ("ALIGN",         (1, 0),  (1, -1),  "RIGHT"),
        ("VALIGN",        (0, 0),  (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0),  (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0),  (-1, -1), 6),
        ("LEFTPADDING",   (0, 0),  (-1, -1), 10),
        ("RIGHTPADDING",  (0, 0),  (-1, -1), 10),
        ("BOX",           (0, 0),  (-1, -1), 0.5, C_BORDER),
        ("INNERGRID",     (0, 0),  (-1, -1), 0.25, C_BORDER),
    ]
    ts_table = Table(tax_rows, colWidths=[USABLE_W * 0.65, USABLE_W * 0.35])
    ts_table.setStyle(TableStyle(ts_style))
    story.append(ts_table)
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "⚠ The estimated taxable income above is calculated by deducting only the expenses "
        "marked as tax-deductible in WandaTools. Actual tax liability depends on applicable "
        "Eswatini Revenue Authority (SRA) rules and rates. This report does not constitute a "
        "tax return. Please consult a registered tax practitioner.",
        S["disclaimer"],
    ))

    # ── Disclaimer ──
    story += _disclaimer("Tax Compliance Summary", period_label, S)

    today = datetime.utcnow().strftime("%Y%m%d")
    safe  = _safe_name(current_user.name or current_user.email)
    buf   = _build_pdf(story, generated_at)
    return _stream(buf, f"TaxCompliance_{safe}_{today}.pdf")
